# Generated by Django 4.1.7 on 2023-04-04 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(max_length=10),
        ),
    ]
