# Generated by Django 4.1.7 on 2023-05-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_calories_alter_food_carbs_alter_food_fat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='protein',
            new_name='proteins',
        ),
    ]
