# Generated by Django 4.1.7 on 2023-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_goal',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carb_goal',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_goal',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein_goal',
            field=models.FloatField(default=0, max_length=25),
        ),
    ]
