# Generated by Django 4.1.7 on 2023-04-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_calories_alter_food_carbs_alter_food_fat_and_more'),
        ('profiles', '0002_alter_profile_calorie_goal_alter_profile_carb_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_goal',
            field=models.FloatField(default=0, max_length=25, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carb_goal',
            field=models.FloatField(default=0, max_length=25, verbose_name='Carb'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_goal',
            field=models.FloatField(default=0, max_length=25, verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein_goal',
            field=models.FloatField(default=0, max_length=25, verbose_name='Protein'),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('foods', models.ManyToManyField(to='foods.food')),
            ],
        ),
    ]
