# Generated by Django 4.1.7 on 2023-04-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_calories_alter_food_carbs_alter_food_fat_and_more'),
        ('profiles', '0003_alter_profile_calorie_goal_alter_profile_carb_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ready', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.AddField(
            model_name='profilefood',
            name='current_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_foods', to='profiles.profilelist'),
        ),
        migrations.AddField(
            model_name='profilefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.food'),
        ),
    ]
