# Generated by Django 4.1.7 on 2023-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilefood_profilelist_delete_userlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
